[project]
name = "profiler"
dynamic = ["version"]
description = "Profiler assigns a clinical profile to a sample given the classification outputs (ClasPar)."
authors = [{name = "Jess Friedersdorff", email = "jess.friedersdorff@ukhsa.gov.uk"}]
requires-python = ">=3.12"
dependencies = ["pandas", "pyyaml", "openpyxl",
"taxaplease@https://github.com/ukhsa-collaboration/gpha-mscape-taxaplease/archive/refs/tags/v2.2.1.tar.gz"]

[tool.setuptools.dynamic]
version = {attr = "profiler.__version__"} # Add underscore separated repo name here

[project.optional-dependencies] # Dependencies for developers only - add more if required
dev = ["ruff", "pytest", "pre-commit"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # comprehesnions
    "C4",
    # pathlib
    "PTH",
]

ignore = ["E501", "UP031"]

[tool.ruff]
line-length = 120

[tool.ruff.format]
quote-style = "double"
